version: "0.2"
language: en
caseSensitive: false
allowCompoundWords: false
useGitignore: true
ignorePaths:
  - "**/{cspell.*,cSpell.*,.cspell.*,cspell.config.*}"
  - "**/node_modules/**"
  - "**/build/**"
  - "**/dist/**"
  - "**/.vscode/**"
  - pnpm-lock.yaml
  - package-lock.json
  - "*.svg"
  - .devcontainer/devcontainer.json
  - go.sum
words:
  - configsources
  - coverprofile
  - cpuid
  - cpus
  - eventstream
  - filippo
  - genkey
  - GOARCH
  - gofmt
  - golangci
  - gopkg
  - hpke
  - imds
  - keygen
  - klauspost
  - mybucket
  - myminio
  - NOFILE
  - softprops
  - ssooidc
  - stretchr
  - taskname
  - urfave
  - zeebo
  - zfsbackup
  - zfsutils
  - zite
