version: "3.7"
services:
  zfs-remote-backup:
    build: .
    container_name: zfs_remote_backup
    privileged: true # for ZFS
    volumes:
      - /mnt:/mnt
      - /dev:/dev
    env_file:
      - .env.local
    # restart: always
